### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Suntrie** [filrech/Trie#1]
0. Использование дефолтного пакета для размещения кода is considered as a [bad practice](https://stackoverflow.com/questions/7849421/is-the-use-of-javas-default-package-a-bad-practice);

1. Что-то пошло не так с областями видимости класса Node. В частности, у Вас в текущей версии кода public метод SearchNode возвращает объект package-private класса TrieNode. Кроме этого, с учетом наличия методов типа searchNode, startsWithThePrefix, можно предположить, что метод search скрывает детали реализации. В таком случае - надо сделать его приватным. Здесь надо либо поправить, либо быть готовым пояснить, почему Вы выбрали именно те модификаторы, которые выбрали;

2. При объявлении переменных стремятся использовать максимально общие типы (Map вместо HashMap и т.д., только инициализируя реализацией интерфейса). Если Вы возвращаете каким-либо геттером, например, просто Map, Вы не заставляете программиста - клиента использовать именно HashMap для хранения (например, если у него есть очень оптимизированный самописный Map, он выиграет). Ну, или ему просто удобнее применять другую реализацию. Для методов более принципиально;

3. Для методов типа add/remove стоит либо выдавать булеву величину в качестве результата (при использовании по назначению), либо выкидывать исключение. Текстовый вывод в разрабатываемом классе не требуется для демонстрации результата, потому что он может быть использован и не в консольном приложении - все результаты возвращаем через возврат return (особенно касается startsWithPrefix). Во время выполнения второй работы у Вас также будет возможность оценить, что тестировать вывод на консоль тоже довольно неудобно:);

4. Поправьте меня, пожалуйста, но, с учетом реализации insert, t.isWord может быть выставлено не только для листьев (если конец слова найден до листа дерева) - и тогда проверку содержания слова целиком стоит поправить. Возможно, где-то среди схоже названных методов есть нужная версия. Сократите, пожалуйста, список публичных методов ровно до тех, что указаны в задании;

5. Для классов, моделирующих данные и работу с ними, необходимо переопределять методы equals и [hashCode](http://tutorials.jenkov.com/java-collections/hashcode-equals.html), с точки зрения удобства отладки стоит также переопределить метод toString.

6. ctrl+C/ctrl+V - "...word.substring(0, word.length() - 1)..." - повторяется весьма часто, заводим переменную и обращаемся непосредственно к ней;

7. Реализация ветки else в remove требует отдельного пояснения (возможно, примеров).

**Comment by filrech** [comment]
7. Если слово является частью другого слова, то оно не должно удаляться из структуры, но должно перестать восприниматься как слово: `t.isWord = false`.

**Comment by filrech** [comment]
4. Попробовал объяснить в комментарии.

**Comment by filrech** [comment]
Остальное вроде исправил

**Comment by Suntrie** [comment]
Остался дефолтный пакет, всё остальное - ок. С точки зрения оформления документации в дальнейшем стоит посмотреть в сторону [javaDoc](http://java-online.ru/java-javadoc.xhtml) - Идея представляет средства генерации стандартной документации на его основе.

Кроме этого, для Maven стоит указывать версию исходников и output (по умолчанию он пытается использовать 1.5) - см. файл "Вопросы и ответы". Кроме этого, в случае Maven-проектов выгружать из служебных файлов можно только pom.xml, остальное будет сгенерировано.
