### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Suntrie** [filrech/Trie#2]
1. Стратегия "1 большой тест" с точки зрения стиля всегда проигрышна, стоит разбить его на несколько тестов поменьше с содержательными названиями;

2. startsWithPrefix сейчас никак не тестируется - поскольку тестирование должно быть автоматизированным (т.е., не человек должен сидеть и сравнить ожидаемое с полученным, а машина; и тестируется опосредованно, да, через booleanStartsWithPrefix - но Вам нужно именно содержимое набора данных, а не факт их наличия, в данном случае).

**Comment by filrech** [comment]
Исправил.

**Comment by Suntrie** [comment]
Пожалуйста, в дальнейшем не закрывайте issues самостоятельно, запутаемся.
